// FileListViewWindowClass.h

#pragma once

#include <windows.h>

#include "..\Common\Ascii.h"
#include "..\Common\Common.h"

#include "FileFindClass.h"
#include "ListViewWindowClass.h"

#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TEXT								NULL
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_MENU								NULL
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE						LVS_EX_FULLROWSELECT
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_STYLE								( WS_CHILD | WS_VISIBLE | WS_BORDER | LBS_NOINTEGRALHEIGHT | LBS_NOTIFY )
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LEFT								0
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TOP									0
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_WIDTH								100
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_HEIGHT								100
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LP_PARAM							NULL

#define FILE_LIST_VIEW_WINDOW_CLASS_POPULATE_STATUS_MESSAGE_FORMAT_STRING		"%d items"

#define FILE_LIST_VIEW_WINDOW_CLASS_COLUMN_TITLES								{ "Name", "Modified" }

typedef enum
{
	FILE_LIST_VIEW_WINDOW_CLASS_NAME_COLUMN_ID = 0,
	FILE_LIST_VIEW_WINDOW_CLASS_MODIFIED_COLUMN_ID,

	FILE_LIST_VIEW_WINDOW_CLASS_NUMBER_OF_COLUMNS

} FILE_LIST_VIEW_WINDOW_CLASS_COLUMNS;

class FileListViewWindow : public ListViewWindow
{
public:
	FileListViewWindow();
	~FileListViewWindow();

	BOOL Create( HWND hWndParent, HINSTANCE hInstance, LPCTSTR lpszWindowText = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TEXT, DWORD dwExStyle = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE, DWORD dwStyle = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_STYLE, int nLeft = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LEFT, int nTop = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TOP, int nWidth = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_WIDTH, int nHeight = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_HEIGHT, HMENU hMenu = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_MENU, LPVOID lpParam = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LP_PARAM );

	BOOL GetItemPath( int nWhichItem, LPTSTR lpszItemPath, DWORD dwTextMax = STRING_LENGTH );

	LRESULT HandleNotifyMessage( HWND hWndMain, WPARAM wParam, LPARAM lParam, BOOL( *lpSelectionChangeFunction )( LPCTSTR lpszItemText ), BOOL( *lpDoubleClickFunction )( LPCTSTR lpszItemText ), PFNLVCOMPARE pFnLvCompare );

	int Populate();

	int Populate( LPCTSTR lpszParentFolderPath );

protected:
	LPTSTR m_lpszParentFolderPath;

}; // End of class FileListViewWindow
