// TemplateListViewWindowClass.h

#pragma once

#include <windows.h>

#include "..\Common\Ascii.h"
#include "..\Common\Common.h"

#include "ListViewWindowClass.h"

#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TEXT							NULL
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_MENU							NULL
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE					0
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_STYLE							( WS_CHILD | WS_VISIBLE | WS_BORDER | LBS_NOINTEGRALHEIGHT | LBS_NOTIFY )
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LEFT							0
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TOP								0
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_WIDTH							100
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_HEIGHT							100
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LP_PARAM						NULL

#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_POPULATE_STATUS_MESSAGE_FORMAT_STRING	"%d items"

#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_COLUMN_TITLES							{ "Column 1", "Column 2" }

typedef enum
{
	TEMPLATE_LIST_VIEW_WINDOW_CLASS_COLUMN_1_ID = 0,
	TEMPLATE_LIST_VIEW_WINDOW_CLASS_COLUMN_2_ID,

	TEMPLATE_LIST_VIEW_WINDOW_CLASS_NUMBER_OF_COLUMNS

} TEMPLATE_LIST_VIEW_WINDOW_CLASS_COLUMNS;

class TemplateListViewWindow : public ListViewWindow
{
public:
	TemplateListViewWindow();
	~TemplateListViewWindow();

	BOOL Create( HWND hWndParent, HINSTANCE hInstance, LPCTSTR lpszWindowText = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TEXT, DWORD dwExStyle = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE, DWORD dwStyle = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_STYLE, int nLeft = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LEFT, int nTop = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TOP, int nWidth = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_WIDTH, int nHeight = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_HEIGHT, HMENU hMenu = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_MENU, LPVOID lpParam = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LP_PARAM );

	LRESULT HandleNotifyMessage( HWND hWndMain, WPARAM wParam, LPARAM lParam, BOOL( *lpSelectionChangeFunction )( LPCTSTR lpszItemText ), BOOL( *lpDoubleClickFunction )( LPCTSTR lpszItemText ), PFNLVCOMPARE pFnLvCompare );

	int Populate();

protected:

}; // End of class TemplateListViewWindow
