// ToolBarWindowClass.h

#pragma once

#include <windows.h>

#include "..\Common\Ascii.h"
#include "..\Common\Common.h"

#include "WindowClass.h"

#define TOOL_BAR_WINDOW_CLASS_NAME												TOOLBARCLASSNAME
#define TOOL_BAR_WINDOW_CLASS_DEFAULT_TEXT										NULL
#define TOOL_BAR_WINDOW_CLASS_DEFAULT_MENU										NULL
#define TOOL_BAR_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE							0
#define TOOL_BAR_WINDOW_CLASS_DEFAULT_STYLE										( WS_CHILD | WS_VISIBLE | TBSTYLE_FLAT | TBSTYLE_WRAPABLE )
#define TOOL_BAR_WINDOW_CLASS_DEFAULT_LEFT										0
#define TOOL_BAR_WINDOW_CLASS_DEFAULT_TOP										0
#define TOOL_BAR_WINDOW_CLASS_DEFAULT_WIDTH										100
#define TOOL_BAR_WINDOW_CLASS_DEFAULT_HEIGHT									100
#define TOOL_BAR_WINDOW_CLASS_DEFAULT_LP_PARAM									NULL

#define TOOL_BAR_WINDOW_CLASS_BUTTON_SIZE										16
#define TOOL_BAR_WINDOW_CLASS_FLAGS												( ILC_COLOR16 | ILC_MASK )
#define TOOL_BAR_WINDOW_CLASS_GROW												0
#define TOOL_BAR_WINDOW_CLASS_IMAGE_LIST_ID										0
#define TOOL_BAR_WINDOW_CLASS_STYLES											BTNS_AUTOSIZE

typedef enum
{
	TOOL_BAR_WINDOW_CLASS_UNDO_BUTTON_ID = 0,
	TOOL_BAR_WINDOW_CLASS_REDO_BUTTON_ID,
	TOOL_BAR_WINDOW_CLASS_CUT_BUTTON_ID,
	TOOL_BAR_WINDOW_CLASS_COPY_BUTTON_ID,
	TOOL_BAR_WINDOW_CLASS_PASTE_BUTTON_ID,
	TOOL_BAR_WINDOW_CLASS_DELETE_BUTTON_ID,
	TOOL_BAR_WINDOW_CLASS_ABOUT_BUTTON_ID,

	TOOL_BAR_WINDOW_CLASS_NUMBER_OF_BUTTONS

} TOOL_BAR_WINDOW_CLASS_BUTTON_IDS;

class ToolBarWindow : public Window
{
public:
	ToolBarWindow();
	~ToolBarWindow();

	int AddButton( int nBitmap, int nCommand );

	BOOL Create( HWND hWndParent, HINSTANCE hInstance, LPCTSTR lpszWindowText = TOOL_BAR_WINDOW_CLASS_DEFAULT_TEXT, DWORD dwExStyle = TOOL_BAR_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE, DWORD dwStyle = TOOL_BAR_WINDOW_CLASS_DEFAULT_STYLE, int nLeft = TOOL_BAR_WINDOW_CLASS_DEFAULT_LEFT, int nTop = TOOL_BAR_WINDOW_CLASS_DEFAULT_TOP, int nWidth = TOOL_BAR_WINDOW_CLASS_DEFAULT_WIDTH, int nHeight = TOOL_BAR_WINDOW_CLASS_DEFAULT_HEIGHT, HMENU hMenu = TOOL_BAR_WINDOW_CLASS_DEFAULT_MENU, LPVOID lpParam = TOOL_BAR_WINDOW_CLASS_DEFAULT_LP_PARAM );

	BOOL EnableButton( int nCommand, BOOL bEnable );

protected:
	HIMAGELIST m_hImageList;
	TBBUTTON m_tbButtons[ TOOL_BAR_WINDOW_CLASS_NUMBER_OF_BUTTONS ];

}; // End of class ToolBarWindow
